# Generated by Django 5.2.11 on 2026-02-21 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CEFRQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.PositiveSmallIntegerField(choices=[(1, 'Part 1 - General Questions'), (2, 'Part 2 - Image Description'), (3, 'Part 3 - Compare/Discuss Images'), (4, 'Part 4 - Discussion')])),
                ('question', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Part 2 va 3 uchun rasm', null=True, upload_to='cefr_images/')),
                ('extra_images', models.JSONField(blank=True, help_text="Part 3 uchun qo'shimcha rasmlar URL ro'yxati", null=True)),
                ('instruction', models.TextField(blank=True, help_text="Foydalanuvchiga ko'rsatma")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CEFR Question',
                'verbose_name_plural': 'CEFR Questions',
            },
        ),
        migrations.CreateModel(
            name='CEFRAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.TextField(blank=True)),
                ('audio_url', models.CharField(blank=True, max_length=500)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cefr_mock.cefrquestion')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CEFRSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('level', models.CharField(blank=True, choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Mastery')], max_length=2, null=True)),
                ('feedback', models.JSONField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('questions', models.ManyToManyField(through='cefr_mock.CEFRAnswer', to='cefr_mock.cefrquestion')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
