# Generated by Django 5.2.10 on 2026-02-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cefr_mock', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cefrquestion',
            name='telegram_file_id',
            field=models.CharField(blank=True, help_text='Bot uchun Telegram rasm file_id (Part 2/3)', max_length=200),
        ),
    ]
