# Generated by Django 5.2.11 on 2026-03-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cefr_mock', '0004_sub_part_stance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEFRPart1_1Question',
            fields=[
            ],
            options={
                'verbose_name': 'CEFR Part 1.1 Savol',
                'verbose_name_plural': '📋 CEFR Part 1.1 — Shaxsiy savollar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cefr_mock.cefrquestion',),
        ),
        migrations.CreateModel(
            name='CEFRPart1_2Question',
            fields=[
            ],
            options={
                'verbose_name': 'CEFR Part 1.2 Savol',
                'verbose_name_plural': '🖼 CEFR Part 1.2 — Rasmli savollar (2 ta)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cefr_mock.cefrquestion',),
        ),
        migrations.CreateModel(
            name='CEFRPart2Question',
            fields=[
            ],
            options={
                'verbose_name': 'CEFR Part 2 Savol',
                'verbose_name_plural': '🃏 CEFR Part 2 — Cue Card',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cefr_mock.cefrquestion',),
        ),
        migrations.CreateModel(
            name='CEFRPart3Question',
            fields=[
            ],
            options={
                'verbose_name': 'CEFR Part 3 Savol',
                'verbose_name_plural': '💬 CEFR Part 3 — FOR / AGAINST',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cefr_mock.cefrquestion',),
        ),
        migrations.AddField(
            model_name='cefrquestion',
            name='image2',
            field=models.ImageField(blank=True, help_text='Part 1.2 uchun 2-rasm', null=True, upload_to='cefr_images/'),
        ),
        migrations.AddField(
            model_name='cefrquestion',
            name='telegram_file_id2',
            field=models.CharField(blank=True, help_text='Bot uchun 2-rasm Telegram file_id', max_length=200),
        ),
        migrations.AlterField(
            model_name='cefrquestion',
            name='telegram_file_id',
            field=models.CharField(blank=True, help_text='Bot uchun Telegram rasm file_id (1-rasm)', max_length=200),
        ),
    ]
