# Generated by Django 5.2.10 on 2026-02-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True)),
                ('full_name', models.CharField(max_length=200)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('activity_type', models.CharField(choices=[('ielts_mock', 'IELTS Mock'), ('cefr_mock', 'CEFR Mock'), ('word_lookup', 'Word Lookup'), ('ai_chat', 'AI Chat'), ('premium_request', "Premium So'rovi")], max_length=30)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bot Faoliyat',
                'verbose_name_plural': 'Bot Faoliyatlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
