# Generated by Django 5.2.11 on 2026-02-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_botactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_photo_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='botactivity',
            name='activity_type',
            field=models.CharField(choices=[('start', 'Bot Start'), ('ielts_mock', 'IELTS Mock'), ('cefr_mock', 'CEFR Mock'), ('word_lookup', 'Word Lookup'), ('ai_chat', 'AI Chat'), ('premium_request', "Premium So'rovi")], max_length=30),
        ),
    ]
