# Generated by Django 5.2.11 on 2026-02-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_gender_photo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTenseStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True)),
                ('date', models.DateField()),
                ('tense_name', models.CharField(max_length=50)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Tense Statistika',
                'verbose_name_plural': 'Tense Statistikalari',
                'unique_together': {('telegram_id', 'date', 'tense_name')},
            },
        ),
    ]
