# Generated by Django 5.2.11 on 2026-03-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_message_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
