# Generated by Django 5.2.11 on 2026-03-14 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_ai_message_count_and_mock_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAdviceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.JSONField(help_text='AI tahlil natijasi (JSON)')),
                ('context_summary', models.TextField(blank=True, help_text='Keyingi tahlil uchun qisqa xulosa (AI tarafidan yoziladi)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advice_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Maslahat Tarixi',
                'verbose_name_plural': 'AI Maslahat Tarixi',
                'ordering': ['-created_at'],
            },
        ),
    ]
