# Generated by Django 5.2.11 on 2026-02-21 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IELTSQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.PositiveSmallIntegerField(choices=[(1, 'Part 1'), (2, 'Part 2 - Cue Card'), (3, 'Part 3')])),
                ('question', models.TextField()),
                ('cue_card_points', models.JSONField(blank=True, help_text='Part 2 uchun - [point1, point2, ...]', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'IELTS Question',
                'verbose_name_plural': 'IELTS Questions',
            },
        ),
        migrations.CreateModel(
            name='IELTSAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.TextField(blank=True)),
                ('audio_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ielts_mock.ieltsquestion')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IELTSSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('overall_band', models.FloatField(blank=True, null=True)),
                ('sub_scores', models.JSONField(blank=True, null=True)),
                ('strengths', models.JSONField(blank=True, null=True)),
                ('improvements', models.JSONField(blank=True, null=True)),
                ('mistakes', models.JSONField(blank=True, null=True)),
                ('recommendations', models.JSONField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('questions', models.ManyToManyField(through='ielts_mock.IELTSAnswer', to='ielts_mock.ieltsquestion')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
