# Generated by Django 5.2.10 on 2026-02-21 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts_mock', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ieltsquestion',
            name='related_part2',
            field=models.ForeignKey(blank=True, help_text='Part 3 uchun: qaysi Part 2 savoliga tegishli?', limit_choices_to={'part': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part3_follow_up', to='ielts_mock.ieltsquestion'),
        ),
    ]
