# Generated by Django 5.2.11 on 2026-03-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts_mock', '0003_ieltsquestion_related_part2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ieltsquestion',
            options={'ordering': ['part', '-is_intro', 'id'], 'verbose_name': 'IELTS Question', 'verbose_name_plural': 'IELTS Questions'},
        ),
        migrations.AddField(
            model_name='ieltsquestion',
            name='is_intro',
            field=models.BooleanField(default=False, help_text="Part 1 da birinchi savol sifatida ishlatiladi. Masalan: 'Can you tell me your name and where you're from?'"),
        ),
        migrations.AlterField(
            model_name='ieltsquestion',
            name='cue_card_points',
            field=models.JSONField(blank=True, help_text='Part 2 uchun — ["Talk about...", "You should say:", "• point1", "• point2"]', null=True),
        ),
    ]
