# Generated by Django 5.2.11 on 2026-03-16 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ielts_mock', '0004_alter_ieltsquestion_options_ieltsquestion_is_intro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IELTSPart1Question',
            fields=[
            ],
            options={
                'verbose_name': 'IELTS Part 1 Savol',
                'verbose_name_plural': '📋 IELTS Part 1 — Savollar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ielts_mock.ieltsquestion',),
        ),
        migrations.CreateModel(
            name='IELTSPart23Set',
            fields=[
            ],
            options={
                'verbose_name': 'IELTS Cue Card (Part 2+3)',
                'verbose_name_plural': '🃏 IELTS Part 2+3 — Cue Cards',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ielts_mock.ieltsquestion',),
        ),
    ]
