# Generated by Django 5.2.11 on 2026-03-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aichat',
            options={'ordering': ['-created_at'], 'verbose_name': 'AI Suhbat', 'verbose_name_plural': 'AI Suhbatlar'},
        ),
        migrations.AddField(
            model_name='aichat',
            name='analysis',
            field=models.TextField(blank=True, help_text='Sessiya oxirida AI tahlil matni'),
        ),
        migrations.AddField(
            model_name='aichat',
            name='coach',
            field=models.CharField(blank=True, default='', help_text='alex yoki emma', max_length=20),
        ),
        migrations.AddField(
            model_name='aichat',
            name='message_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aichat',
            name='tense_stats',
            field=models.JSONField(blank=True, help_text='Zamonlar statistikasi', null=True),
        ),
    ]
