# Generated by Django 5.2.11 on 2026-03-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_practicecategory_category_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practicescenario',
            options={'ordering': ['difficulty', 'title'], 'verbose_name': 'Practice Scenario', 'verbose_name_plural': 'Practice Scenarios'},
        ),
        migrations.AddField(
            model_name='practicecategory',
            name='description',
            field=models.TextField(blank=True, help_text='Kategoriya haqida qisqacha'),
        ),
        migrations.AddField(
            model_name='practicecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='practicemessage',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practicescenario',
            name='ai_role',
            field=models.CharField(blank=True, default='', help_text="AI qanday rol o'ynaydi (masalan: Waiter, Doctor, Interviewer)", max_length=100),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='analysis_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='fluency_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='grammar_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='pronunciation_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='tense_stats',
            field=models.JSONField(blank=True, help_text="{'present_simple': {'total': 10, 'correct': 8, 'percent': 80}, ...}", null=True),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='vocab_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='practicecategory',
            name='category_type',
            field=models.CharField(choices=[('real_life', 'Real Life Situations'), ('academic', 'Academic Conversations')], default='real_life', max_length=10),
        ),
        migrations.AlterField(
            model_name='practicecategory',
            name='icon',
            field=models.CharField(default='🗣', max_length=10),
        ),
        migrations.AlterField(
            model_name='practicescenario',
            name='ai_prompt',
            field=models.TextField(help_text="AI uchun sistema prompt — faqat admin ko'radi, user ko'rmaydi"),
        ),
        migrations.AlterField(
            model_name='practicescenario',
            name='description',
            field=models.TextField(help_text="Foydalanuvchiga ko'rsatiladigan qisqacha tavsif"),
        ),
        migrations.AlterField(
            model_name='practicescenario',
            name='what_to_expect',
            field=models.TextField(blank=True, help_text="Bu sessiyada nima bo'ladi — har bir qatorga bitta narsa yozing"),
        ),
    ]
