# Generated by Django 5.2.11 on 2026-02-22 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_calls_limit', models.PositiveIntegerField(default=3, help_text="Yangi foydalanuvchilar uchun bepul qo'ng'iroqlar soni")),
                ('referrals_for_premium', models.PositiveIntegerField(default=3, help_text='Bepul premium olish uchun zarur referal soni')),
                ('referral_premium_days', models.PositiveIntegerField(default=30, help_text='Referal orqali beriladigan bepul premium kunlar soni')),
                ('web_app_url', models.URLField(blank=True, help_text='Telegram Web App URL (masalan: https://yourdomain.com/webapp/)')),
            ],
            options={
                'verbose_name': 'App Sozlamalari',
                'verbose_name_plural': 'App Sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(help_text='Karta raqami (masalan: 8600 1234 5678 9012)', max_length=25)),
                ('owner_name', models.CharField(help_text='Karta egasining ismi', max_length=100)),
                ('bank_name', models.CharField(blank=True, default='', help_text='Bank nomi (masalan: Uzcard, Humo)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text="Faqat 1 ta karta aktiv bo'lishi kerak")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "To'lov Kartasi",
                'verbose_name_plural': "To'lov Kartalari",
            },
        ),
        migrations.CreateModel(
            name='RequiredChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_title', models.CharField(help_text="Kanal nomi (ko'rsatish uchun)", max_length=100)),
                ('channel_username', models.CharField(help_text="@username (@ belgisisiz ham bo'ladi)", max_length=100)),
                ('channel_link', models.URLField(help_text='t.me/username havolasi')),
                ('is_active', models.BooleanField(default=True, help_text='Bu kanalga obunani tekshirish')),
                ('is_bot_admin', models.BooleanField(default=False, editable=False, help_text='Bot kanalda admin ekanligi (avtomatik tekshiriladi)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Majburiy Kanal',
                'verbose_name_plural': 'Majburiy Kanallar',
            },
        ),
        migrations.CreateModel(
            name='VoiceRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_type', models.CharField(choices=[('human', 'Inson'), ('ai', 'AI')], default='human', max_length=10)),
                ('status', models.CharField(choices=[('searching', 'Qidirilmoqda'), ('active', 'Faol'), ('ended', 'Tugadi')], default='searching', max_length=15)),
                ('gender_filter', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol'), ('any', 'Har qanday')], default='any', max_length=10)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('any', 'Any Level')], default='any', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_rooms_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_rooms_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ovozli Suhbat Xonasi',
                'verbose_name_plural': 'Ovozli Suhbat Xonalari',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_voice_ratings', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_voice_ratings', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='webapp.voiceroom')),
            ],
            options={
                'verbose_name': 'Suhbat Baholash',
                'verbose_name_plural': 'Suhbat Baholashlar',
                'unique_together': {('room', 'rater')},
            },
        ),
    ]
