# Generated by Django 5.2.11 on 2026-03-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_add_aimessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='free_ai_calls_limit',
            field=models.PositiveIntegerField(default=10, help_text="Premium bo'lmagan user nechta AI call qila oladi", verbose_name="Bepul AI qo'ng'iroqlar"),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='free_cefr_limit',
            field=models.PositiveIntegerField(default=2, help_text="Premium bo'lmagan user nechta CEFR Mock topshira oladi", verbose_name='Bepul CEFR Mock testlar'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='free_ielts_limit',
            field=models.PositiveIntegerField(default=2, help_text="Premium bo'lmagan user nechta IELTS Mock topshira oladi", verbose_name='Bepul IELTS Mock testlar'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='free_practice_limit',
            field=models.PositiveIntegerField(default=3, help_text="Premium bo'lmagan user nechta Practice sessiya o'tkazishi mumkin", verbose_name='Bepul Practice sessiyalar'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='maintenance_message',
            field=models.TextField(blank=True, default="🔧 Texnik ishlar olib borilmoqda. Iltimos, keyinroq urinib ko'ring.", verbose_name='Texnik ishlar xabari'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text="Yoqilsa bot faqat 'Texnik ishlar' xabarini yuboradi", verbose_name='Texnik ishlar rejimi'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='premium_expiry_reminder_days',
            field=models.PositiveIntegerField(default=1, help_text='Premium tugashidan necha kun oldin foydalanuvchiga xabar yuborilsin', verbose_name='Premium tugashi eslatmasi (kun oldin)'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='free_calls_limit',
            field=models.PositiveIntegerField(default=5, help_text="Premium bo'lmagan user nechta real partner call qila oladi", verbose_name="Bepul qo'ng'iroqlar (Speaking)"),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='referral_premium_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Referal orqali beriladigan premium (kun)'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='referrals_for_premium',
            field=models.PositiveIntegerField(default=5, verbose_name='Premium uchun talab qilinadigan referallar soni'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='web_app_url',
            field=models.URLField(blank=True, help_text='Telegram Web App havolasi', verbose_name='Web App URL'),
        ),
    ]
