# Generated by Django 5.2.11 on 2026-03-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_appsettings_free_ai_calls_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='free_ai_message_limit',
            field=models.PositiveIntegerField(default=40, help_text="Premium bo'lmagan user nechta AI chat xabari yuborishi mumkin", verbose_name='Bepul AI xabarlari soni'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='free_total_mock_limit',
            field=models.PositiveIntegerField(default=2, help_text='Bitta user nechta mock test topshira oladi (IELTS+CEFR hammasi)', verbose_name='Bepul jami Mock (IELTS+CEFR)'),
        ),
    ]
