# Generated by Django 5.2.10 on 2026-02-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumpurchase',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='premiumpurchase',
            name='receipt_image',
            field=models.ImageField(blank=True, help_text="To'lov cheki rasmi", null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='premiumpurchase',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
