# Generated by Django 5.2.11 on 2026-02-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0003_premiumpurchase_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumplan',
            name='price_uzs',
            field=models.PositiveIntegerField(default=0, help_text="Narx (so'm)"),
        ),
        migrations.AlterField(
            model_name='premiumplan',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
