# Generated by Django 5.2.11 on 2026-02-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('chats_count', models.PositiveIntegerField(default=0)),
                ('practice_count', models.PositiveIntegerField(default=0)),
                ('ielts_score', models.FloatField(blank=True, null=True)),
                ('cefr_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('words_learned', models.PositiveIntegerField(default=0)),
                ('report_data', models.JSONField(default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
