# Generated by Django 5.2.10 on 2026-02-21 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Broadcast nomi (foydalanuvchiga ko'rinmaydi)", max_length=200)),
                ('message', models.TextField(help_text='Yuborilinadigan xabar matni')),
                ('image', models.ImageField(blank=True, help_text='Rasm (ixtiyoriy)', null=True, upload_to='broadcasts/')),
                ('link', models.URLField(blank=True, help_text='Tugma linki (ixtiyoriy)')),
                ('button_text', models.CharField(blank=True, default='🔗 Batafsil', help_text='Tugma matni', max_length=100)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Broadcast',
                'verbose_name_plural': 'Broadcastlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
